name: ptu_cgpa_tracker
description: CGPA calculator and tracker for PTU students

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.1.0
  lottie: ^1.0.1
  connectivity_wrapper: ^1.0.6
  flutter_svg: ^0.22.0 
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.4
  cloud_firestore: ^2.2.1
  firebase_core: ^1.2.1
  admob_flutter: ^1.0.1

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/no.webp
    - assets/net.json
    - assets/1234.svg
    - assets/undraw_Calculator_0evy.png
    - assets/456.jpg
    - assets/sanj.jpg
    - assets/ashok.jpg
    - assets/yuva.jpeg
    - assets/yadav.jpg