name: ptu_cgpa_tracker
description: CGPA calculator and tracker for PTU students

version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.0.1
  connectivity_wrapper: ^1.0.6
  flutter_svg: ^0.22.0 
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.4
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  shared_preferences: ^2.0.6
  google_mobile_ads: ^0.13.2
  share: ^2.0.4


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
    
